### ISSUE TITLE
bug report for `kcl-openapi generate model --crd`: regex.match()

### ISSUE THREAD

**Issue by howieyuen** [kcl-lang/kcl-openapi#29]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```bash
kcl-openapi generate model --crd -f crd/alertmanagerconfigs.yaml  -t . --skip-validation
```

### 2. What did you expect to see? (Required)

1. for keyword  `check`, use `regex.match()` instead of `matchPattern()`
2. import statement is not match with konfig base models

```
import kusion_kubernetes.apimachinery.apis

...

check:
    regex.match(enforcedBodySizeLimit, r"(^0|([0-9]*[.])?[0-9]+((K|M|G|T|E|P)i?)?B)$") if enforcedBodySizeLimit
```

### 3. What did you see instead (Required)

```
import base.pkg.kusion_kubernetes.apimachinery.apis

...

check:
    matchPattern(enforcedBodySizeLimit, (^0|([0-9]*[.])?[0-9]+((K|M|G|T|E|P)i?)?B)$)
```

### 4. What is your KusionStack components version? (Required)

```
gitInfo:
    latestTag: v0.7.0
    commit: 414a12b275f4a7a6849b19266f91f7a3ebdbc3e5
    treeState: clean
buildInfo:
    goVersion: go1.17.13
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-10-17 03:29:32"
dependency:
    kclvmgoVersion: v0.4.3-alpha.4
    kclPluginVersion: v0.4.1-alpha2
```
