### ISSUE TITLE
[Bug] the version information may be missed if the crd uses Spec.Versions instead of Spec.Version to set the version

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl-openapi#67]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

the crd:

```
# Deprecated in v1.16 in favor of apiextensions.k8s.io/v1
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ct
  preserveUnknownFields: false

```

### 2. What did you expect to see? (Required)

the generated file: `stable_example_com_v1_cron_tab.k` and the contents will contain "apiVersion : str, default is "stable.example.com/v1", required"

### 3. What did you see instead (Required)

the generated file: `stable_example_com_cron_tab.k`, and the apiVersion line is "apiVersion : str, default is "stable.example.com/", required"
